### ISSUE TITLE
SBSUIWallpaperSetImage can randomly corrupt the wallpaper cache file saved on disk on iOS 13.3

### ISSUE THREAD

**Issue by JeffResc** [captinc/WallpaperChanger#1] opened 2020-06-01 23:57 UTC
Hey @captinc,

I used parts of this project in my tweak to change the wallpaper. Shortly after publishing, SparkDev reached out to me stating that SBSUIWallpaperSetImage can randomly corrupt the wallpaper cache file saved on disk on iOS 13.3 and possibly iOS 13.5, but he didn't test that version.

I just thought that I would forward the information he gave to me to you:
```
Hey, just saw your wallpaper setting tweak and thought I should let you know:

I pulled my tweak FreshWall which does a similar thing, to change it to use a different method.

SBSUIWallpaperSetImage has an issue on 13.3 (haven’t checked on 13.5 yet) that can seemingly randomly corrupt the wallpaper cache file saved on disk. The result of this is eventually springboard crashes repeatedly, and if you reboot you get stuck in a bootloop.

I’d recommend pulling this and switching to a non persistent method of setting the wallpaper (or at least a method that doesn’t use this function), because it’s going to cause issues at least for the people on <13.5 and maybe even 13.5.

And at the end of the day, any tweak that changes things on disk that are relied on by the system has the potential to bootloop the device. So it’s always better practice to only do things at runtime. (I learned this the hard way through FreshWall)

The issue appeared in 13.1 or later also, it was never an issue on 12
```

Let me know if you have any questions :)

**Comment by captinc** [comment] 2020-06-02 00:03
Yikes. Thanks for reaching out. What code should I use instead?

**Comment by JeffResc** [comment] 2020-06-02 00:04
I haven't updated my code yet either, he didn't mention what new method he uses. I'll reply here once I find an equivalent function

**Comment by captinc** [comment] 2020-06-02 00:13
Just so you don’t go on a wild goose chase, when I first made this tweak, I looked high and low for the right method. This is the only way I could find that worked on iOS 13

**Comment by JeffResc** [comment] 2020-06-02 00:15
Spark didn't mention the new method that he used, but he mentioned to do everything at runtime and to hook runtime methods:
```
So yeah, I’ve got a build of mine together hooking a few methods in the wallpaper view itself (so nothing will get modified on disk) - so probably a plan to move to something like that :)
```

**Comment by captinc** [comment] 2020-06-02 00:19
Darn. I kinda wanted my tweak to mirror exactly what Settings.app does & persist into nonjailbroken state (obviously without bootlooping tho.... 😬)

**Comment by JeffResc** [comment] 2020-06-02 21:31
I’ll try to play around with it tonight in my free time with Frida and attempt to find what Settings.app uses. I wonder why it corrupts over time though... 🤔

**Comment by JeffResc** [comment] 2020-06-03 01:20
I just looked into this a bit. It looks like the SpringBoard calls this method, which I haven't investigated too much yet, but it looks promising...
`-[SBFWallpaperConfigurationManager setWallpaperImage:0x2833f6d90 adjustedImage:0x2833f7de0 thumbnailData:0x280b7ebc0 wallpaperOptions:0x282b3ad60 forVariants:0x3 wallpaperMode:0x0]`

[Link to header file with this method](https://developer.limneos.net/?ios=13.1.3&framework=SpringBoardFoundation.framework&header=SBFWallpaperConfigurationManager.h).

**Comment by captinc** [comment] 2020-06-03 03:11
Cool! Keep me posted, thanks so much!

**Comment by JeffResc** [comment] 2020-06-03 03:18
I've been working on this for almost two hours now with no luck. I can't find a proper initializer for the class for some reason. The `initialize` method returns void, not id, so that doesn't work and the `init` method returns id, but is an instance method, so it's useless. Stumped on this one :/

**Comment by captinc** [comment] 2020-06-03 03:35
lol both things you just said are wrong😂. Here lemme explain

+ (void)initialize is not what you want, for obvious reasons. This method exists in every NSObject & all subclasses of NSObject. This method is the **first** method called whenever you create an object. It is only called once per object, and (as you can guess), initializes some stuff that iOS needs

Although class methods (stuff that have +) make our lives very easy, they are not required. You can create an instance of any object with the below method call. For some objects, it will totally initialize the object, but won’t for others. All depends on how Apple coded it

ClassName *thisObject = [[ClassName alloc] init];

I just checked in FLEX, and alloc > init totally sets up SBFWallpaperConfigurationManager, so we’re lucky this time! After a brief look around, I think this is what we should investigate further: 

SBFWallpaperConfigurationManager *man = [[SBFWallpaperConfigurationManager alloc] init];

[man setWallpaperImage:arg1 wallpaperOptions:arg2 forVariants:arg3];

I’m not positive, but I think arg1 should be a UIImage of the wanted picture. arg2 is probably SBFWallpaperOptions. arg3 is a NSInteger that specifies whether to set the home screen, lock screen, or both

WallpaperChanger has code for what I suspect arg2 and arg3 are, so you can look at that to get ideas. 80% chance that WallpaperChanger’s existing code will work for arg2 and arg3

And finally, I don’t have time to investigate this further right now, but I will get to it as soon as possible. But keep me updated on how it goes & feel free to ask any questions - I can still respond. Thanks again man!

Edit: one more thing - you can always hook setWallpaperImage:wallpaperOptions:forVariants & log the arguments. This will tell you what each argument’s class & possibly each arg’s value. After hooking, just try to set a wallpaper in settings and see what happens

**Comment by JeffResc** [comment] 2020-06-03 03:54
Hey, thanks for the reply even though my information was wrong, this is only second published tweak and I'm still learning the terminology. A lot of these terms don't exist in the other languages that I've learned so I haven't been the best at picking up the terms for things.

Anyways, I think I implemented what you said above correctly. It compiles, but I'm still getting a runtime error about an unrecognized selector, but I've verified the headers exist on Limneos' site (unless they changed in 13.5), but maybe I just implemented it wrong...

```objc
@interface SBFWallpaperConfigurationManager
+(id)alloc;
-(id)init;
-(BOOL)setWallpaperImage:(id)arg1 wallpaperOptions:(id)arg2 forVariants:(long long)arg3 wallpaperMode:(long long)arg4;
@end

SBFWallpaperConfigurationManager *wallpaperManager = [[objc_getClass("SBFWallpaperConfigurationManager") alloc] init];
[wallpaperManager setWallpaperImage:newImage wallpaperOptions:options forVariants:location wallpaperMode:0];
```
```
2020-06-02 23:50:47.858 dynamikcli[7073:663915] -[SBFWallpaperConfigurationManager setWallpaperImage:wallpaperOptions:forVariants:wallpaperMode:]: unrecognized selector sent to instance 0x1029408e0
2020-06-02 23:50:47.859 dynamikcli[7073:663915] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBFWallpaperConfigurationManager setWallpaperImage:wallpaperOptions:forVariants:wallpaperMode:]: unrecognized selector sent to instance 0x1029408e0'
*** First throw call stack:
(0x1b1054300 0x1b0d68c1c 0x1b0f52a90 0x1b1058a60 0x1b105ad60 0x1028714b8 0x102871aa4 0x1b0e452dc)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by JeffResc** [comment] 2020-06-05 00:04
Hm, maybe it was a false lead, I've tried this new code and it does nothing, no error, but no success either
```objc
SBFWallpaperConfigurationManager *wallpaperManager = [[objc_getClass("SBFWallpaperConfigurationManager") alloc] init];
[wallpaperManager setWallpaperImage:newImage wallpaperOptions:options forVariants:location];
```

**Comment by captinc** [comment] 2020-06-05 00:53
What are you using for options and location?

**Comment by JeffResc** [comment] 2020-06-05 00:56
Oops, sorry for not including that the first time. I tried location as 1, 2 and 3 (as integers), just like the SBSUIWallpaperSetImage did and options is set to
```objc
id options = [[objc_getClass("SBFWallpaperOptions") alloc] init];
```

**Comment by captinc** [comment] 2020-06-05 01:00
Did you set the appropriate properties for “options”?

**Comment by JeffResc** [comment] 2020-06-05 04:00
Not sure, first I initialized them [like you did here](https://github.com/captinc/WallpaperChanger/blob/master/main.m#L22-L23), but I did not add the `setWallpaperMode` selector [like you did](https://github.com/captinc/WallpaperChanger/blob/master/main.m#L33-L34) because I wasn't sure about how that worked because there isn't a separate light and dark image for `SBFWallpaperConfigurationManager setWallpaperImage`.

**Comment by captinc** [comment] 2020-06-05 04:25
Darn. Idk then. I guess we have to keep looking in FLEX. Did Spark say anything more?

**Comment by JeffResc** [comment] 2020-06-09 00:45
Nope, I contacted him on June 2 and I haven't heard anything back, still looking at alternative methods though

**Closed as completed** 2021-05-11 17:02 UTC

**Comment by captinc** [comment] 2021-05-11 17:10
There has not been much activity on this thread for awhile now, and I have not heard about nor discovered any new information since, so I'm going to close it. I still have not found the root cause, whatever it was. Perhaps it was a bug on Apple's part, who knows. ¯\_(ツ)_/¯ If new information is found in the future, feel free to bring it up again.

**Comment by MrGcGamer** [comment] 2023-01-13 18:57
Don't know if anyone will ever see this but still:
To get a working instance of `SBFWallpaperConfigurationManager` one can use the `SBWallpaperController` like this:
```objc
SBWallpaperController *wallpaperController = [objc_getClass("SBWallpaperController") sharedInstance];
SBFWallpaperConfigurationManager *confManager = [wallpaperController wallpaperConfigurationManager];

[confManager setWallpaperImage:newWallpaper wallpaperOptions:options forVariants:location];
```

Based on the disassembly (only looked at the iOS 15 versions), this method does not seem to call `SBSUIWallpaperSetImage(s)`, so it might or might not be safe to use.

EDIT:
This method does not trigger the SB update notification though.
